apiVersion: v1
kind: Service
metadata:
  name: redis04-node
  labels:
    app: redis04-node
spec:
  type: NodePort
  selector:
    app: redis04
    appCluster: redis-cluster
  ports:
  - name: redis04
    port: 7004
    targetPort: 6380
    protocol: TCP
    nodePort: 30004
  - name: redis01-control
    port: 17004
    targetPort: 16380
    protocol: TCP
    nodePort: 31004
