apiVersion: v1
kind: Service
metadata:
  name: redis02-node
  labels:
    app: redis02-node
spec:
  type: NodePort
  selector:
    app: redis02
    appCluster: redis-cluster
  ports:
  - name: redis02
    port: 7002
    targetPort: 6380
    protocol: TCP
    nodePort: 30002
  - name: redis02-control
    port: 17002
    targetPort: 16380
    protocol: TCP
    nodePort: 31002
