apiVersion: v1
kind: Service
metadata:
  name: redis01-node
  labels:
    app: redis01-node
spec:
  type: NodePort
  selector:
    app: redis01
    appCluster: redis-cluster
  ports:
  - name: redis01
    port: 7001
    targetPort: 6380
    protocol: TCP
    nodePort: 30001
  - name: redis01-control
    port: 17001
    targetPort: 16380
    protocol: TCP
    nodePort: 31001
