apiVersion: v1
kind: Service
metadata:
  name: redis06-node
  labels:
    app: redis06-node
spec:
  type: NodePort
  selector:
    app: redis06
    appCluster: redis-cluster
  ports:
  - name: redis06
    port: 7006
    targetPort: 6380
    protocol: TCP
    nodePort: 30006
  - name: redis01-control
    port: 17006
    targetPort: 16380
    protocol: TCP
    nodePort: 31006
