apiVersion: v1
kind: Service
metadata:
  name: redis05-node
  labels:
    app: redis05-node
spec:
  type: NodePort
  selector:
    app: redis05
    appCluster: redis-cluster
  ports:
  - name: redis05
    port: 7005
    targetPort: 6380
    protocol: TCP
    nodePort: 30005
  - name: redis01-control
    port: 17005
    targetPort: 16380
    protocol: TCP
    nodePort: 31005
