apiVersion: v1
kind: Service
metadata:
  name: redis-node
  labels:
    app: redis-node
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
    nodePort: 30379
  - name: redis-control
    port: 16379
    targetPort: 16379
    protocol: TCP
    nodePort: 31379
