apiVersion: v1
kind: Service
metadata:
  name: redis03-node
  labels:
    app: redis03-node
spec:
  type: NodePort
  selector:
    app: redis03
    appCluster: redis-cluster
  ports:
  - name: redis03
    port: 7003
    targetPort: 6380
    protocol: TCP
    nodePort: 30003
  - name: redis03-control
    port: 17003
    targetPort: 16380
    protocol: TCP
    nodePort: 31003
